apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec: 
  containers:
  #docker run -d --name nginx
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
    command ["sleep 100"]